"""initial schema v2

Revision ID: 20615846ae46
Revises: 
Create Date: 2026-06-11 12:39:28.360209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20615846ae46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_event_source_id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('historical_traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('road_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_mph', sa.Float(), nullable=True),
    sa.Column('free_flow_speed_mph', sa.Float(), nullable=True),
    sa.Column('congestion_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hist_segment_ts', 'historical_traffic', ['segment_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_historical_traffic_id'), 'historical_traffic', ['id'], unique=False)
    op.create_index(op.f('ix_historical_traffic_segment_id'), 'historical_traffic', ['segment_id'], unique=False)
    op.create_index(op.f('ix_historical_traffic_timestamp'), 'historical_traffic', ['timestamp'], unique=False)
    op.create_table('live_traffic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('road_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_mph', sa.Float(), nullable=True),
    sa.Column('free_flow_speed_mph', sa.Float(), nullable=True),
    sa.Column('congestion_level', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_traffic_cache_id'), 'live_traffic_cache', ['id'], unique=False)
    op.create_index(op.f('ix_live_traffic_cache_segment_id'), 'live_traffic_cache', ['segment_id'], unique=True)
    op.create_table('traffic_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_incidents_id'), 'traffic_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_incidents_incident_id'), 'traffic_incidents', ['incident_id'], unique=True)
    op.create_table('traffic_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('road_name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_segments_id'), 'traffic_segments', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_segments_segment_id'), 'traffic_segments', ['segment_id'], unique=True)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('precipitation_in', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('rain_alert', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_id'), 'weather_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_timestamp'), 'weather_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_snapshots_timestamp'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_id'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_traffic_segments_segment_id'), table_name='traffic_segments')
    op.drop_index(op.f('ix_traffic_segments_id'), table_name='traffic_segments')
    op.drop_table('traffic_segments')
    op.drop_index(op.f('ix_traffic_incidents_incident_id'), table_name='traffic_incidents')
    op.drop_index(op.f('ix_traffic_incidents_id'), table_name='traffic_incidents')
    op.drop_table('traffic_incidents')
    op.drop_index(op.f('ix_live_traffic_cache_segment_id'), table_name='live_traffic_cache')
    op.drop_index(op.f('ix_live_traffic_cache_id'), table_name='live_traffic_cache')
    op.drop_table('live_traffic_cache')
    op.drop_index(op.f('ix_historical_traffic_timestamp'), table_name='historical_traffic')
    op.drop_index(op.f('ix_historical_traffic_segment_id'), table_name='historical_traffic')
    op.drop_index(op.f('ix_historical_traffic_id'), table_name='historical_traffic')
    op.drop_index('ix_hist_segment_ts', table_name='historical_traffic')
    op.drop_table('historical_traffic')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
