"""initial_schema

Revision ID: 49b0509b6388
Revises: 
Create Date: 2026-06-02 00:20:52.413733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49b0509b6388'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merged_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corridor_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('current_speed_mph', sa.Float(), nullable=True),
    sa.Column('free_flow_speed_mph', sa.Float(), nullable=True),
    sa.Column('current_travel_time_sec', sa.Float(), nullable=True),
    sa.Column('free_flow_travel_time_sec', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('congestion_index', sa.Float(), nullable=True),
    sa.Column('nearest_weather_zone', sa.String(), nullable=True),
    sa.Column('weather_zone_dist_mi', sa.Float(), nullable=True),
    sa.Column('weather_condition_id', sa.Integer(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('weather_temp_f', sa.Float(), nullable=True),
    sa.Column('weather_feels_like_f', sa.Float(), nullable=True),
    sa.Column('weather_humidity_pct', sa.Float(), nullable=True),
    sa.Column('weather_visibility_mi', sa.Float(), nullable=True),
    sa.Column('weather_wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('weather_wind_gust_mph', sa.Float(), nullable=True),
    sa.Column('weather_rain_1h_mm', sa.Float(), nullable=True),
    sa.Column('weather_snow_1h_mm', sa.Float(), nullable=True),
    sa.Column('weather_cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('weather_traffic_impact_level', sa.String(), nullable=True),
    sa.Column('nearby_event_count', sa.Integer(), nullable=True),
    sa.Column('has_high_impact_event', sa.Boolean(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'corridor_name', name='uq_merged_ts_corridor')
    )
    op.create_index(op.f('ix_merged_features_corridor_name'), 'merged_features', ['corridor_name'], unique=False)
    op.create_index(op.f('ix_merged_features_id'), 'merged_features', ['id'], unique=False)
    op.create_index(op.f('ix_merged_features_timestamp'), 'merged_features', ['timestamp'], unique=False)
    op.create_table('ticketmaster_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.String(), nullable=True),
    sa.Column('event_time_local', sa.String(), nullable=True),
    sa.Column('classification_segment', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('is_high_traffic_impact', sa.Boolean(), nullable=True),
    sa.Column('venue_name', sa.String(), nullable=True),
    sa.Column('venue_city', sa.String(), nullable=True),
    sa.Column('venue_latitude', sa.Float(), nullable=True),
    sa.Column('venue_longitude', sa.Float(), nullable=True),
    sa.Column('venue_capacity', sa.Integer(), nullable=True),
    sa.Column('ticket_min_price_usd', sa.Float(), nullable=True),
    sa.Column('ticket_max_price_usd', sa.Float(), nullable=True),
    sa.Column('est_congestion_radius_mi', sa.Float(), nullable=True),
    sa.Column('event_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticketmaster_events_event_id'), 'ticketmaster_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_ticketmaster_events_id'), 'ticketmaster_events', ['id'], unique=False)
    op.create_index(op.f('ix_ticketmaster_events_timestamp'), 'ticketmaster_events', ['timestamp'], unique=False)
    op.create_table('traffic_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corridor_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('current_speed_mph', sa.Float(), nullable=True),
    sa.Column('free_flow_speed_mph', sa.Float(), nullable=True),
    sa.Column('current_travel_time_sec', sa.Float(), nullable=True),
    sa.Column('free_flow_travel_time_sec', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('congestion_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_readings_corridor_name'), 'traffic_readings', ['corridor_name'], unique=False)
    op.create_index(op.f('ix_traffic_readings_id'), 'traffic_readings', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_readings_timestamp'), 'traffic_readings', ['timestamp'], unique=False)
    op.create_table('weather_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('feels_like_f', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('visibility_mi', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('wind_gust_mph', sa.Float(), nullable=True),
    sa.Column('rain_1h_mm', sa.Float(), nullable=True),
    sa.Column('snow_1h_mm', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('traffic_impact_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_conditions_id'), 'weather_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_weather_conditions_timestamp'), 'weather_conditions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_weather_conditions_zone_name'), 'weather_conditions', ['zone_name'], unique=False)
    op.drop_geospatial_index(op.f('idx_geo_events_venue_location'), table_name='geo_events', postgresql_using='gist', column_name='venue_location')
    op.drop_index(op.f('ix_geo_events_external_id'), table_name='geo_events')
    op.drop_index(op.f('ix_geo_events_id'), table_name='geo_events')
    op.drop_index(op.f('ix_geo_events_start_time'), table_name='geo_events')
    op.drop_geospatial_table('geo_events')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_road_segments_id'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_name'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_osm_id'), table_name='road_segments')
    op.drop_index(op.f('ix_traffic_observations_id'), table_name='traffic_observations')
    op.drop_index(op.f('ix_weather_snapshots_id'), table_name='weather_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weather_snapshots_id'), 'weather_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_observations_id'), 'traffic_observations', ['id'], unique=False)
    op.create_index(op.f('ix_road_segments_osm_id'), 'road_segments', ['osm_id'], unique=False)
    op.create_index(op.f('ix_road_segments_name'), 'road_segments', ['name'], unique=False)
    op.create_index(op.f('ix_road_segments_id'), 'road_segments', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_geospatial_table('geo_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('venue_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expected_attendance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_high_impact', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('est_congestion_radius_mi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('geo_events_pkey'))
    )
    op.create_index(op.f('ix_geo_events_start_time'), 'geo_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_geo_events_id'), 'geo_events', ['id'], unique=False)
    op.create_index(op.f('ix_geo_events_external_id'), 'geo_events', ['external_id'], unique=True)
    op.create_geospatial_index(op.f('idx_geo_events_venue_location'), 'geo_events', ['venue_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_index(op.f('ix_weather_conditions_zone_name'), table_name='weather_conditions')
    op.drop_index(op.f('ix_weather_conditions_timestamp'), table_name='weather_conditions')
    op.drop_index(op.f('ix_weather_conditions_id'), table_name='weather_conditions')
    op.drop_table('weather_conditions')
    op.drop_index(op.f('ix_traffic_readings_timestamp'), table_name='traffic_readings')
    op.drop_index(op.f('ix_traffic_readings_id'), table_name='traffic_readings')
    op.drop_index(op.f('ix_traffic_readings_corridor_name'), table_name='traffic_readings')
    op.drop_table('traffic_readings')
    op.drop_index(op.f('ix_ticketmaster_events_timestamp'), table_name='ticketmaster_events')
    op.drop_index(op.f('ix_ticketmaster_events_id'), table_name='ticketmaster_events')
    op.drop_index(op.f('ix_ticketmaster_events_event_id'), table_name='ticketmaster_events')
    op.drop_table('ticketmaster_events')
    op.drop_index(op.f('ix_merged_features_timestamp'), table_name='merged_features')
    op.drop_index(op.f('ix_merged_features_id'), table_name='merged_features')
    op.drop_index(op.f('ix_merged_features_corridor_name'), table_name='merged_features')
    op.drop_table('merged_features')
    # ### end Alembic commands ###
